version: '1.5'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nextjs13-wealth
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    